# Generated by Django 3.1.3 on 2020-11-13 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20201112_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-created_at'], 'verbose_name_plural': '컨텐츠'},
        ),
    ]
